version: '3.7'

services:
  my-express-app:
    image: my-express-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - '3004:3004'
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
